#!/usr/bin/env bash

IGNORE_NEW=""

_batdiff() {
  if ! git rev-parse --is-inside-work-tree 1>/dev/null; then
    exit 1
  fi

  repo_root=$(git rev-parse --show-toplevel)
  return_to=$(pwd)

  cd "$repo_root" || exit

  if [ -z "$IGNORE_NEW" ]; then
    git add --intent-to-add .
  fi

  changed_files=$(git diff --name-only --diff-filter=d)
  new_files=$(git ls-files --others --exclude-standard)

  echo "$changed_files $new_files" | xargs printf -- "%s\n" | xargs bat --diff

  if [ -z "$IGNORE_NEW" ]; then
    git reset --mixed 1>/dev/null
  fi

  cd "$return_to" || exit
}

_git_diff() {
  while [ "$1" != "" ]; do
    case $1 in
    -i | --ignore-new)
      IGNORE_NEW="TRUE"
      ;;
    esac
    shift
  done

  if command -v bat 1>/dev/null 2>&1; then
    _batdiff
  else
    git diff
  fi
}

_git_diff "$@"
