window:
  dynamic_padding: true
  decorations: buttonless
  opacity: 0.95
  padding:
    y: 5

shell:
  program: /usr/local/bin/fish
  args:
    - --login
    - -C command -v zellij-work && zellij-work || zellij

colors:
  primary:
    background: '#101010'
    foreground: '#5ee39b'

  cursor:
    cursor: '#f81ce6'

  normal:
    black: '#313131'
    red: '#ff6262'
    green: '#1DC121'
    yellow: '#C7C329'
    blue: '#3eb5ff'
    magenta: '#C839C5'
    cyan: '#20C5C6'
    white: '#C7C7C7'

  bright:
    Black: '#686868'
    Red: '#FD6F6B'
    Green: '#67F86F'
    Yellow: '#FFFA72'
    Blue: '#7accff'
    Magenta: '#FD7CFC'
    Cyan: '#68FDFE'
    White: '#FFFFFF'

# alt_send_esc: false

key_bindings:
  - { key: 28, mods: Alt|Shift, chars: '{' }
  - { key: 25, mods: Alt|Shift, chars: '}' }
  - { key: 37, mods: Alt, chars: '@' }
  - { key: 26, mods: Alt|Shift, chars: "\\" }
  - { key: 26, mods: Alt, chars: '|' }
  - { key: 45, mods: Alt, chars: '~' }
  - { key: 23, mods: Alt, chars: '[' }
  - { key: 22, mods: Alt, chars: ']' }
