#!/usr/bin/env bash

git log --graph --format=format:'%C(bold blue)%h%C(reset) %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white)— %an%C(reset)%C(auto)%d%C(reset)' --abbrev-commit --date=relative
