# FROM ubuntu:jammy
FROM public.ecr.aws/docker/library/ubuntu:noble
# RUN apk add git util-linux
# RUN apt-get update && apt-get install -y git util-linux curl
RUN sudo locale-gen en_US.UTF-8
RUN apt-get update
RUN apt-get install -y git util-linux curl
