name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          echo "uggaaaa"

